sudo: false

branches:
  except:
    - debian
    - khronos-registry

os:
  - linux

compiler:
  - gcc
  - clang

language:
  - c

services:
  - docker

before_install:
  - docker pull ebassi/epoxyci

before_script:
  - echo FROM ebassi/epoxyci > Dockerfile
  - echo ADD . /root >> Dockerfile
  - docker build -t withgit .

script:
  - docker run withgit /bin/sh -c "CC=$CC ./epoxy-run-tests.sh"
  - docker run withgit /bin/sh -c "CC=$CC ./epoxy-run-tests.sh -Denable-glx=no"
  - docker run withgit /bin/sh -c "CC=$CC ./epoxy-run-tests.sh -Denable-egl=no"
